spring:
  profiles:
    active: @spring.profiles.active@

book-dictionary:
  books:
    -
      title: "Git Pocket Guide"
      author: "Richard E. Silverman"
      publisher: "O'Reilly Media"
    -
      title: "Learning JavaScript Design Patterns"
      author: "Addy Osmani"
      publisher: "O'Reilly Media"
    -
      title: "Designing Evolvable Web APIs with ASP.NET"
      author: "Glenn Block et al."
      publisher: "O'Reilly Media"
    -
      title: "Speaking JavaScript"
      author: "Axel Rauschmayer"
      publisher: "O'Reilly Media"
    -
      title: "You Don't Know JS"
      author: "Kyle Simpson"
      publisher: "O'Reilly Media"
    -
      title: "Programming JavaScript Applications"
      author: "Eric Elliott"
      publisher: "O'Reilly Media"